version: "3.8"

services:
  pixelhunter:
    build: .
    container_name: pixelhunter
    volumes:
      - ./models:/app/models
      - ./datasets:/app/datasets
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
